---
- name: Install node and npm
  hosts: 172.31.8.99
  tasks:
    - name: Update apt repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Install nodejs and npm
      apt:
        pkg:
          - nodejs
          - npm


- name: Create new linux user for node app
  hosts: 172.31.8.99
  tasks:
    - name: Create linux user
      user:
        name: antoine
        comment: Node User
        group: admin


- name: Deploy nodejs app
  hosts: 172.31.8.99
  become: True
  become_user: antoine  
  tasks:
    - name: Clone a github repository
      git:
        repo: git@github.com:kevAnto/node-app-c.git
        dest: /home/ubuntu/repos
        clone: yes
        update: yes
    - name: Unpack the nodejs file
      unarchive:
        src: /home/ubuntu/repos/node-app-c/nodejs-app-1.0.0.tgz
        dest: /home/antoine
    - name: Install dependencies
      npm:
        path: /home/antoine/package
    - name: Start the application
      command:
        chdir: /home/antoine/package/app
        cmd: node server
      async: 1000
      poll: 0
    - name: Ensure app is running
      shell: ps aux | grep node
      register: app_status
    - debug: msg={{app_status.stdout_lines}}
